---
title: "Air Quality"
author: ""
date: "2020/6/6"
output: html_document
---

```{r setup, warning=FALSE, message=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(car)
library(tidyverse)
library(glmnet)
library(pls)
library(genridge)
```

## Part 1: EDA

```{r}
data <- read.csv("wanshouxigong_20130301-20170228.csv") ## read the data

wd <- function(x){ ## convert wd into "North or not"
  if(x %in% c("N", "NE", "NNE", "NNW", "NW", "WNW")){
    return("Yes")
  }
  else{return("No")}
}

# PM2.5 lag data
data$lag1 <- c(NA, data[1:(dim(data)[1]-1),]$PM2.5) 
data$lag2 <- c(NA, NA, data[1:(dim(data)[1]-2),]$PM2.5) 
data$lag3 <- c(NA, NA, NA, data[1:(dim(data)[1]-3),]$PM2.5)
data$lag4 <- c(NA, NA, NA, NA, data[1:(dim(data)[1]-4),]$PM2.5)
data$wd <- sapply(data$wd, wd)
colnames(data)[16] <- "north"

#climate lag 1
climate.lag <- rbind(data[1, 12:17], data[1:(nrow(data)-1), 12:17])
data <- cbind(data, climate.lag)

lag <- data[c(6, 19:28)] %>% na.omit()
```

```{r}
lag_gather <- lag %>%
  gather(key = "varname", value = "value", lag1, lag2, lag3, lag4)

# Figure 1: First 4 lag variables
ggplot(data = lag_gather) +
  geom_point(aes(x = PM2.5, y = value), size = 1) +
  facet_wrap(~ varname) +
  theme_classic() +
  labs(x = "PM2.5(current)", y = "PM2.5(lag)") +
  theme(axis.title = element_text(size = 15),
        axis.text = element_text(size = 12),
        strip.text = element_text(size = 12))
```

```{r}
cor(lag$PM2.5, lag$lag1)
cor(lag$PM2.5, lag$lag2)
cor(lag$PM2.5, lag$lag3)
cor(lag$PM2.5, lag$lag4)
```

```{r}
corr_lag <- function(x){
  lag <- c(rep(NA, x), data[1:(dim(data)[1]-x),]$PM2.5)
  tmp <- data.frame(now = data$PM2.5,
                    lag = lag) %>% na.omit()
  return(cor(tmp$lag, tmp$now))
}

# Figure 2: Lag length and correlation
ggplot(data = data.frame(num = 1:10, corr = sapply(1:10, corr_lag))) +
  geom_line(aes(x = num, y = corr), size = 1) +
  geom_point(aes(x = num, y = corr), size = 2) +
  labs(x = "Lag length (hour)", y = "correlation coefficient") +
  scale_x_continuous(breaks = 1:10, labels = 1:10) +
  theme_classic() +
  theme(axis.title = element_text(size = 15), axis.text = element_text(size = 12))
```

```{r}
data1 <- read.csv("wanshouxigong_20130301-20170228.csv") %>%
  select(year, month, day, PM2.5, wd) %>%
  filter(year < 2017) %>%
  na.omit()
```

```{r}
level <- function(x){
  if(x < 35){return(1)}
  else if(x < 75){return(2)}
  else if(x < 115){return(3)}
  else if(x < 150){return(4)}
  else if(x < 250){return(5)}
  else{return(6)}
}
# create new level
data1$level = factor(sapply(data1$PM2.5, level), levels = c(6, 5, 4, 3, 2, 1))
```

```{r}
#Figure 3: Wind speed and PM2.5
ggplot(data = data1) +
  geom_bar(aes(x = wd, group = level, fill = level), position = "fill") +
  scale_fill_manual(breaks = c(1, 4, 2, 5, 3, 6), 
                    values = c("#3D0000", "#910000", "red", "orange", "yellow", "green"),
                    name = element_blank(),
                    labels = c(expression(PM[2.5]*"<35"*mu*"g/"*m^3),
                               expression("115"*mu*"g/"*m^3*"<"*PM[2.5]*"<150"*mu*"g/"*m^3),
                               expression("35"*mu*"g/"*m^3*"<"*PM[2.5]*"<75"*mu*"g/"*m^3),
                               expression("150"*mu*"g/"*m^3*"<"*PM[2.5]*"<250"*mu*"g/"*m^3),
                               expression("75"*mu*"g/"*m^3*"<"*PM[2.5]*"<115"*mu*"g/"*m^3),
                               expression(PM[2.5]*">250"*mu*"g/"*m^3))) +
  scale_y_continuous(breaks = seq(0.2, 1, 0.2), labels = seq(0.2, 1, 0.2)) +
  labs(y = "Percentage") +
  theme_classic() +
  theme(legend.position = "bottom",
        axis.title.x = element_blank(),
        axis.title.y = element_text(angle = 0, vjust = 1, size = 8),
        axis.text.x = element_text(angle = 30, vjust = 0.5, size = 8),
        axis.text.y = element_text(size = 8),
        legend.text = element_text(hjust = 0, size = 10),
        strip.background = element_blank(),
        strip.text = element_text(size = 10))

```

```{r, warning=FALSE}
climate.gather <- lag[c(1, 6:11)] %>%
  gather(key = "varname", value = "value", -PM2.5)

climate.gather.continuous <- climate.gather %>%
  filter(varname != "north")

climate.gather.discrete <- climate.gather %>%
  filter(varname == "north")

labels <- c(DEWP = "Low Temp", PRES = "Pressure", RAIN = "Rainfall",
            TEMP = "High Temp", north = "WD (north or not)", WSPM = "Wind Speed")

# Figure 4: EDA for all climate predictors
ggplot(data = climate.gather) +
  geom_point(aes(x = value, y = PM2.5) , data = climate.gather.continuous, size = 0.7) +
  geom_boxplot(aes(x = value, y = PM2.5) , data = climate.gather.discrete) +
  facet_wrap(~ varname, scales = "free", labeller = labeller(varname = labels)) +
  labs(x = "Climate Date", y = "PM2.5") +
  theme_classic() +
  theme(axis.title = element_text(size = 12),
        axis.text = element_blank(),
        strip.text = element_text(size = 10))
```

## Part 2: Full Model

### 2.1 Performance on training set

```{r}
train <- lag[1:30000, ]
test <- lag[30001:nrow(lag), ]
feb18.2017 <- data[34801:34824, ] ## extract specific day for testing
```

```{r}
full.model <- lm(PM2.5 ~ ., data = train)
```

```{r}
### RMSE
rmse <- function(y, y_pred){
  return(sqrt(mean((y-y_pred)^2)))
}

rmse(predict(full.model, train), train[["PM2.5"]])
```

### 2.2 Performance on test data

```{r}
rmse(predict(full.model, test), test[["PM2.5"]])
```

Performance on a specific day (in test data)

```{r}
conf <- predict(full.model, feb18.2017, interval = "prediction")
conf <- data.frame(conf)
conf$true <- feb18.2017$PM2.5
conf$hour <- 1:24 - 0.5
```

```{r}
# Figure 6: Ridge regression prediction and CI on Feb 2, 2017
ggplot(data = conf %>% gather(key = "key", value = "value", true, fit), aes(x = hour)) +
  geom_point(aes(y = value, color = key), size = 2) +
  geom_line(data = conf, aes(x = hour, y = fit), color = "red", size = 1) +
  geom_ribbon(data = conf, aes(x = hour, ymin = lwr, ymax = upr), alpha = 0.2) +
  labs(x = "Time (2017.2.18)", y = "RM2.5") +
  scale_x_continuous(limits = c(0, 27), breaks = seq(0, 24, 4), labels = seq(0, 24, 4)) +
  scale_color_discrete(name = element_blank(), labels = c("Prediction", "True value")) +
  theme_classic() +
  theme(axis.title = element_text(size = 15),
        axis.text = element_text(size = 12),
        legend.text = element_text(size = 12),
        legend.background = element_rect(colour = "black"),
        legend.position=c(.93,.5))
```

## Part 3 Variable Selection

```{r}
# BIC (k = log(n))
bic <- step(full.model, k = log(nrow(train)))
```

```{r}
summary(bic)
```

```{r}
# diagnose plot
par(mfrow = c(2, 2))
plot(bic)
```

```{r}
rmse(predict(bic, train), train[["PM2.5"]])
rmse(predict(bic, test), test[["PM2.5"]])
```

## Part 4: Ridge Regression

```{r}
# starting from bic model
x.train <- model.matrix(PM2.5~.-lag4-PRES, train)[,-1]
y.train <- train$PM2.5
x.test <- model.matrix(PM2.5~.-lag4-PRES, test)[,-1]
y.test <- test$PM2.5

grid <- 10 ^ seq(-0.5, -1.5, length = 100)
ridge.mod <- glmnet(x.train, y.train, alpha = 0, lambda = grid)
pred <- predict.glmnet(ridge.mod, newx = x.test, s = grid)
RMSE <- apply(pred, 2, rmse, y.test)

# Figure 5: CV for ridge regression
ggplot(data = data.frame(lambda = grid, rmse = RMSE)) +
  geom_line(aes(x = log(lambda), y = rmse), size = 1.5) +
  geom_vline(aes(xintercept = log(grid[RMSE == min(RMSE)])), size = 1, colour = "red") +
  labs(x = "log-lambda", y = "RMSE for test data") +
  theme_classic() +
  theme(axis.title = element_text(size = 12), axis.text = element_text(size = 10))
```

```{r}
predict.glmnet(ridge.mod, newx = x.test, s = grid[RMSE == min(RMSE)], type = "coefficients")
```


```{r}
min(RMSE)
grid[RMSE == min(RMSE)]
```